/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import AppDao.minhasFinancasDao;
import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.ColorUIResource;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gabriel.fbroschel
 */
public class PaginaPrincipal extends javax.swing.JFrame {

    private int id;

    /**
     * Creates new form PaginaPrincipal
     */
    public PaginaPrincipal() {
        initComponents();

    }

    public PaginaPrincipal(int id) {
        initComponents();
        this.id = id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        btnDespesas = new javax.swing.JButton();
        btnReceitas = new javax.swing.JButton();
        btnMetas = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();
        panelDespesas = new javax.swing.JPanel();
        lblTexto1 = new javax.swing.JLabel();
        txtDescricaoDesp = new javax.swing.JTextField();
        lblTexto2 = new javax.swing.JLabel();
        txtValorDesp = new javax.swing.JTextField();
        lblTexto3 = new javax.swing.JLabel();
        txtDataDesp = new javax.swing.JFormattedTextField();
        lblTexto = new javax.swing.JLabel();
        cmbCategoriaDesp = new javax.swing.JComboBox<>();
        btnCriarDespesa = new javax.swing.JButton();
        lblTituloDespesa = new javax.swing.JLabel();
        lblFundoDespesa = new javax.swing.JLabel();
        panelMetas = new javax.swing.JPanel();
        lblTexto8 = new javax.swing.JLabel();
        txtDescricaoMeta = new javax.swing.JTextField();
        lblTexto9 = new javax.swing.JLabel();
        txtValorMeta = new javax.swing.JTextField();
        lblTexto10 = new javax.swing.JLabel();
        txtDataInicialMeta = new javax.swing.JFormattedTextField();
        txtDataFinalMeta = new javax.swing.JFormattedTextField();
        lblTexto11 = new javax.swing.JLabel();
        btnCriarMeta = new javax.swing.JButton();
        btnExcluirMeta = new javax.swing.JButton();
        lblTituloMetas = new javax.swing.JLabel();
        lblfundoMetas = new javax.swing.JLabel();
        scrPanelMetas = new javax.swing.JScrollPane();
        tblMetas = new javax.swing.JTable();
        panelRelatorio = new javax.swing.JPanel();
        lblTituloRelatorio = new javax.swing.JLabel();
        scrPanelRelatorio = new javax.swing.JScrollPane();
        tblRelatorio = new javax.swing.JTable();
        lblFundoRelatorio = new javax.swing.JLabel();
        panelOrcamentos = new javax.swing.JPanel();
        lblTituloOrcamento = new javax.swing.JLabel();
        lblFundoOrcamento = new javax.swing.JLabel();
        panelReceitas = new javax.swing.JPanel();
        lblTexto4 = new javax.swing.JLabel();
        txtDescricaoRec = new javax.swing.JTextField();
        lblTexto5 = new javax.swing.JLabel();
        txtValorRec = new javax.swing.JTextField();
        lblTexto6 = new javax.swing.JLabel();
        txtDataRec = new javax.swing.JFormattedTextField();
        lblTexto7 = new javax.swing.JLabel();
        cmbCategoriaRec = new javax.swing.JComboBox<>();
        btnCriarReceita = new javax.swing.JButton();
        lblTituloReceitas = new javax.swing.JLabel();
        lblFundoReceitas = new javax.swing.JLabel();
        panelDesMensal = new javax.swing.JPanel();
        lblDespMen = new javax.swing.JLabel();
        lblMostrarDespesa = new javax.swing.JLabel();
        panelRecMensal = new javax.swing.JPanel();
        lblRecMen1 = new javax.swing.JLabel();
        lblMostrarReceita = new javax.swing.JLabel();
        panelSaldoGeral = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblSaldoGeral = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblLogo2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        menuPrincipal = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        jMenuBar2.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar2.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar2.setOpaque(true);

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MinhasFinanças");
        setExtendedState(MAXIMIZED_BOTH
        );
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        btnDespesas.setBackground(new java.awt.Color(239, 248, 255));
        btnDespesas.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        btnDespesas.setForeground(new java.awt.Color(20, 33, 56));
        btnDespesas.setText("Despesas");
        btnDespesas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDespesasActionPerformed(evt);
            }
        });
        getContentPane().add(btnDespesas);
        btnDespesas.setBounds(50, 240, 130, 110);

        btnReceitas.setBackground(new java.awt.Color(239, 248, 255));
        btnReceitas.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        btnReceitas.setForeground(new java.awt.Color(20, 33, 56));
        btnReceitas.setText("Receitas");
        btnReceitas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReceitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceitasActionPerformed(evt);
            }
        });
        getContentPane().add(btnReceitas);
        btnReceitas.setBounds(50, 370, 130, 110);

        btnMetas.setBackground(new java.awt.Color(239, 248, 255));
        btnMetas.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        btnMetas.setForeground(new java.awt.Color(20, 33, 56));
        btnMetas.setText("Metas");
        btnMetas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetasActionPerformed(evt);
            }
        });
        getContentPane().add(btnMetas);
        btnMetas.setBounds(50, 510, 130, 110);

        btnRelatorio.setBackground(new java.awt.Color(239, 248, 255));
        btnRelatorio.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        btnRelatorio.setForeground(new java.awt.Color(20, 33, 56));
        btnRelatorio.setText("Relatorio");
        btnRelatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });
        getContentPane().add(btnRelatorio);
        btnRelatorio.setBounds(50, 640, 130, 110);

        panelDespesas.setBackground(new java.awt.Color(123, 194, 145));
        panelDespesas.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 51)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102), 2)));
        panelDespesas.setEnabled(false);
        panelDespesas.setVisible(false);
        panelDespesas.setLayout(null);

        lblTexto1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        lblTexto1.setForeground(new java.awt.Color(20, 33, 56));
        lblTexto1.setText("Descrição:");
        panelDespesas.add(lblTexto1);
        lblTexto1.setBounds(110, 180, 110, 30);

        txtDescricaoDesp.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        panelDespesas.add(txtDescricaoDesp);
        txtDescricaoDesp.setBounds(100, 210, 570, 40);

        lblTexto2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        lblTexto2.setForeground(new java.awt.Color(20, 33, 56));
        lblTexto2.setText("Valor:");
        panelDespesas.add(lblTexto2);
        lblTexto2.setBounds(110, 290, 70, 30);

        txtValorDesp.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        txtValorDesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorDespActionPerformed(evt);
            }
        });
        panelDespesas.add(txtValorDesp);
        txtValorDesp.setBounds(100, 320, 570, 40);

        lblTexto3.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        lblTexto3.setForeground(new java.awt.Color(20, 33, 56));
        lblTexto3.setText("Data ( ano - mês - dia ):");
        panelDespesas.add(lblTexto3);
        lblTexto3.setBounds(110, 400, 240, 30);

        try {
            txtDataDesp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataDesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataDespActionPerformed(evt);
            }
        });
        panelDespesas.add(txtDataDesp);
        txtDataDesp.setBounds(100, 430, 570, 40);

        lblTexto.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        lblTexto.setForeground(new java.awt.Color(20, 33, 56));
        lblTexto.setText("Categoria:");
        panelDespesas.add(lblTexto);
        lblTexto.setBounds(110, 510, 110, 30);

        cmbCategoriaDesp.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        cmbCategoriaDesp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Alimentação", "Assinaturas e Serviços", "Bares e Restaurantes", "Casa", "Compras", "Cuidados Pessoais", "Dívidas e Empréstimos", "Educação", "Família e Filhos", "Impostos e Taxas", "Investimentos", "Lazer e Hobbies", "Mercado", "Pets", "Presentes e Doações", "Roupas", "Saúde", "Trabalho", "Transporte", "Viagem", "Outros" }));
        panelDespesas.add(cmbCategoriaDesp);
        cmbCategoriaDesp.setBounds(100, 540, 570, 50);

        btnCriarDespesa.setBackground(new java.awt.Color(123, 194, 145));
        btnCriarDespesa.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        btnCriarDespesa.setForeground(new java.awt.Color(20, 33, 56));
        btnCriarDespesa.setText("Criar Despesa");
        btnCriarDespesa.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 33, 56))));
        btnCriarDespesa.setOpaque(true);
        btnCriarDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarDespesaActionPerformed(evt);
            }
        });
        panelDespesas.add(btnCriarDespesa);
        btnCriarDespesa.setBounds(260, 660, 260, 90);

        lblTituloDespesa.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 36)); // NOI18N
        lblTituloDespesa.setForeground(new java.awt.Color(20, 33, 56));
        lblTituloDespesa.setText("DESPESAS");
        panelDespesas.add(lblTituloDespesa);
        lblTituloDespesa.setBounds(280, 70, 180, 50);

        lblFundoDespesa.setBackground(new java.awt.Color(239, 248, 255));
        lblFundoDespesa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102), 2));
        lblFundoDespesa.setOpaque(true);
        panelDespesas.add(lblFundoDespesa);
        lblFundoDespesa.setBounds(40, 40, 690, 840);

        getContentPane().add(panelDespesas);
        panelDespesas.setBounds(230, 30, 770, 920);

        panelMetas.setBackground(new java.awt.Color(123, 194, 145));
        panelMetas.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 51)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102), 2)));
        panelMetas.setEnabled(false);
        panelMetas.setVisible(false);
        panelMetas.setLayout(null);

        lblTexto8.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        lblTexto8.setForeground(new java.awt.Color(20, 33, 56));
        lblTexto8.setText("Descrição:");
        panelMetas.add(lblTexto8);
        lblTexto8.setBounds(110, 180, 110, 30);

        txtDescricaoMeta.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        panelMetas.add(txtDescricaoMeta);
        txtDescricaoMeta.setBounds(100, 210, 570, 40);

        lblTexto9.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        lblTexto9.setForeground(new java.awt.Color(20, 33, 56));
        lblTexto9.setText("Valor:");
        panelMetas.add(lblTexto9);
        lblTexto9.setBounds(110, 290, 70, 30);

        txtValorMeta.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        panelMetas.add(txtValorMeta);
        txtValorMeta.setBounds(100, 320, 570, 40);

        lblTexto10.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        lblTexto10.setForeground(new java.awt.Color(20, 33, 56));
        lblTexto10.setText("Data inicial:");
        panelMetas.add(lblTexto10);
        lblTexto10.setBounds(110, 400, 130, 30);

        try {
            txtDataInicialMeta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        panelMetas.add(txtDataInicialMeta);
        txtDataInicialMeta.setBounds(100, 430, 570, 40);

        try {
            txtDataFinalMeta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        panelMetas.add(txtDataFinalMeta);
        txtDataFinalMeta.setBounds(100, 550, 570, 40);

        lblTexto11.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        lblTexto11.setForeground(new java.awt.Color(20, 33, 56));
        lblTexto11.setText("Data Final:");
        panelMetas.add(lblTexto11);
        lblTexto11.setBounds(110, 520, 130, 30);

        btnCriarMeta.setBackground(new java.awt.Color(123, 194, 145));
        btnCriarMeta.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        btnCriarMeta.setForeground(new java.awt.Color(20, 33, 56));
        btnCriarMeta.setText("Criar");
        btnCriarMeta.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 33, 56))));
        btnCriarMeta.setOpaque(true);
        btnCriarMeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarMetaActionPerformed(evt);
            }
        });
        panelMetas.add(btnCriarMeta);
        btnCriarMeta.setBounds(240, 660, 260, 90);

        btnExcluirMeta.setBackground(new java.awt.Color(123, 194, 145));
        btnExcluirMeta.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        btnExcluirMeta.setForeground(new java.awt.Color(20, 33, 56));
        btnExcluirMeta.setText("Excluir ");
        btnExcluirMeta.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 33, 56))));
        btnExcluirMeta.setOpaque(true);
        btnExcluirMeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirMetaActionPerformed(evt);
            }
        });
        panelMetas.add(btnExcluirMeta);
        btnExcluirMeta.setBounds(290, 760, 150, 50);

        lblTituloMetas.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 36)); // NOI18N
        lblTituloMetas.setForeground(new java.awt.Color(20, 33, 56));
        lblTituloMetas.setText("METAS");
        panelMetas.add(lblTituloMetas);
        lblTituloMetas.setBounds(320, 80, 120, 50);

        lblfundoMetas.setBackground(new java.awt.Color(239, 248, 255));
        lblfundoMetas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102), 2));
        lblfundoMetas.setOpaque(true);
        panelMetas.add(lblfundoMetas);
        lblfundoMetas.setBounds(40, 40, 690, 840);

        tblMetas.setBackground(new java.awt.Color(239, 248, 255));
        tblMetas.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        tblMetas.setForeground(new java.awt.Color(20, 33, 56));
        tblMetas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "n°", "Descrição", "Valor", "Data Inicial", "Data Final"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMetas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        tblMetas.setGridColor(new java.awt.Color(0, 153, 102));
        tblMetas.setRowHeight(40);
        tblMetas.setSelectionBackground(new java.awt.Color(1, 10, 27));
        tblMetas.setShowGrid(false);
        scrPanelMetas.setViewportView(tblMetas);

        panelMetas.add(scrPanelMetas);
        scrPanelMetas.setBounds(770, 40, 730, 840);

        getContentPane().add(panelMetas);
        panelMetas.setBounds(230, 30, 1580, 920);

        panelRelatorio.setBackground(new java.awt.Color(123, 194, 145));
        panelRelatorio.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 51)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102), 2)));
        panelRelatorio.setEnabled(false);
        panelRelatorio.setVisible(false);
        panelRelatorio.setLayout(null);

        lblTituloRelatorio.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 36)); // NOI18N
        lblTituloRelatorio.setForeground(new java.awt.Color(20, 33, 56));
        lblTituloRelatorio.setText("RELATÓRIO");
        panelRelatorio.add(lblTituloRelatorio);
        lblTituloRelatorio.setBounds(280, 70, 190, 50);

        tblRelatorio.setBackground(new java.awt.Color(239, 248, 255));
        tblRelatorio.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        tblRelatorio.setForeground(new java.awt.Color(20, 33, 56));
        tblRelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Data", "Entrada", "Saída", "Saldo"
            }
        ));
        tblRelatorio.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        tblRelatorio.setGridColor(new java.awt.Color(0, 153, 102));
        tblRelatorio.setRowHeight(40);
        tblRelatorio.setSelectionBackground(new java.awt.Color(1, 10, 27));
        scrPanelRelatorio.setViewportView(tblRelatorio);
        tblRelatorio.getAccessibleContext().setAccessibleParent(tblRelatorio);

        panelRelatorio.add(scrPanelRelatorio);
        scrPanelRelatorio.setBounds(90, 130, 590, 730);

        lblFundoRelatorio.setBackground(new java.awt.Color(239, 248, 255));
        lblFundoRelatorio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102), 2));
        lblFundoRelatorio.setOpaque(true);
        panelRelatorio.add(lblFundoRelatorio);
        lblFundoRelatorio.setBounds(40, 40, 690, 840);

        getContentPane().add(panelRelatorio);
        panelRelatorio.setBounds(230, 30, 770, 920);

        panelOrcamentos.setBackground(new java.awt.Color(123, 194, 145));
        panelOrcamentos.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 51)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102), 2)));
        panelOrcamentos.setEnabled(false);
        panelOrcamentos.setVisible(false);
        panelOrcamentos.setLayout(null);

        lblTituloOrcamento.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 36)); // NOI18N
        lblTituloOrcamento.setForeground(new java.awt.Color(20, 33, 56));
        lblTituloOrcamento.setText("ORÇAMENTOS");
        panelOrcamentos.add(lblTituloOrcamento);
        lblTituloOrcamento.setBounds(250, 70, 240, 50);

        lblFundoOrcamento.setBackground(new java.awt.Color(239, 248, 255));
        lblFundoOrcamento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102), 2));
        lblFundoOrcamento.setOpaque(true);
        panelOrcamentos.add(lblFundoOrcamento);
        lblFundoOrcamento.setBounds(40, 40, 690, 840);

        getContentPane().add(panelOrcamentos);
        panelOrcamentos.setBounds(230, 30, 770, 920);

        panelReceitas.setBackground(new java.awt.Color(123, 194, 145));
        panelReceitas.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 51)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102), 2)));
        panelReceitas.setEnabled(false);
        panelReceitas.setVisible(false);
        panelReceitas.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                panelReceitasAncestorRemoved(evt);
            }
        });
        panelReceitas.setLayout(null);

        lblTexto4.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        lblTexto4.setForeground(new java.awt.Color(20, 33, 56));
        lblTexto4.setText("Descrição:");
        panelReceitas.add(lblTexto4);
        lblTexto4.setBounds(110, 180, 110, 30);

        txtDescricaoRec.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        panelReceitas.add(txtDescricaoRec);
        txtDescricaoRec.setBounds(100, 210, 570, 40);

        lblTexto5.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        lblTexto5.setForeground(new java.awt.Color(20, 33, 56));
        lblTexto5.setText("Valor:");
        panelReceitas.add(lblTexto5);
        lblTexto5.setBounds(110, 290, 70, 30);

        txtValorRec.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        panelReceitas.add(txtValorRec);
        txtValorRec.setBounds(100, 320, 570, 40);

        lblTexto6.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        lblTexto6.setForeground(new java.awt.Color(20, 33, 56));
        lblTexto6.setText("Data ( ano - mês - dia ):");
        panelReceitas.add(lblTexto6);
        lblTexto6.setBounds(110, 400, 240, 30);

        try {
            txtDataRec.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        panelReceitas.add(txtDataRec);
        txtDataRec.setBounds(100, 430, 570, 40);

        lblTexto7.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        lblTexto7.setForeground(new java.awt.Color(20, 33, 56));
        lblTexto7.setText("Categoria:");
        panelReceitas.add(lblTexto7);
        lblTexto7.setBounds(110, 510, 110, 30);

        cmbCategoriaRec.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        cmbCategoriaRec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Empréstimos", "Investimentos", "Salário", "Outras Receitas" }));
        panelReceitas.add(cmbCategoriaRec);
        cmbCategoriaRec.setBounds(100, 540, 570, 50);

        btnCriarReceita.setBackground(new java.awt.Color(123, 194, 145));
        btnCriarReceita.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        btnCriarReceita.setForeground(new java.awt.Color(20, 33, 56));
        btnCriarReceita.setText("Criar Receita");
        btnCriarReceita.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 33, 56))));
        btnCriarReceita.setOpaque(true);
        btnCriarReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarReceitaActionPerformed(evt);
            }
        });
        panelReceitas.add(btnCriarReceita);
        btnCriarReceita.setBounds(260, 660, 260, 90);

        lblTituloReceitas.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 36)); // NOI18N
        lblTituloReceitas.setForeground(new java.awt.Color(20, 33, 56));
        lblTituloReceitas.setText("RECEITAS");
        panelReceitas.add(lblTituloReceitas);
        lblTituloReceitas.setBounds(280, 70, 170, 50);

        lblFundoReceitas.setBackground(new java.awt.Color(239, 248, 255));
        lblFundoReceitas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102), 2));
        lblFundoReceitas.setOpaque(true);
        panelReceitas.add(lblFundoReceitas);
        lblFundoReceitas.setBounds(40, 40, 690, 840);

        getContentPane().add(panelReceitas);
        panelReceitas.setBounds(230, 30, 770, 920);

        panelDesMensal.setBackground(new java.awt.Color(1, 10, 27));
        panelDesMensal.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 217, 210), java.awt.Color.lightGray)));
        panelDesMensal.setLayout(null);

        lblDespMen.setBackground(new java.awt.Color(255, 255, 255));
        lblDespMen.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 48)); // NOI18N
        lblDespMen.setForeground(new java.awt.Color(255, 217, 210));
        lblDespMen.setText("Despesas");
        panelDesMensal.add(lblDespMen);
        lblDespMen.setBounds(240, 10, 210, 50);

        lblMostrarDespesa.setBackground(new java.awt.Color(221, 221, 221));
        lblMostrarDespesa.setFont(new java.awt.Font("Ebrima", 0, 36)); // NOI18N
        lblMostrarDespesa.setForeground(new java.awt.Color(251, 251, 251));
        lblMostrarDespesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMostrarDespesa.setToolTipText("");
        panelDesMensal.add(lblMostrarDespesa);
        lblMostrarDespesa.setBounds(0, 70, 690, 70);

        getContentPane().add(panelDesMensal);
        panelDesMensal.setBounds(1120, 600, 690, 190);

        panelRecMensal.setBackground(new java.awt.Color(1, 10, 27));
        panelRecMensal.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 217, 210), java.awt.Color.lightGray)));
        panelRecMensal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelRecMensal.setName(""); // NOI18N
        panelRecMensal.setLayout(null);

        lblRecMen1.setBackground(new java.awt.Color(255, 255, 255));
        lblRecMen1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 48)); // NOI18N
        lblRecMen1.setForeground(new java.awt.Color(255, 217, 210));
        lblRecMen1.setText("Receita");
        panelRecMensal.add(lblRecMen1);
        lblRecMen1.setBounds(260, 10, 160, 50);

        lblMostrarReceita.setBackground(new java.awt.Color(221, 221, 221));
        lblMostrarReceita.setFont(new java.awt.Font("Ebrima", 0, 36)); // NOI18N
        lblMostrarReceita.setForeground(new java.awt.Color(251, 251, 251));
        lblMostrarReceita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelRecMensal.add(lblMostrarReceita);
        lblMostrarReceita.setBounds(0, 70, 690, 70);

        getContentPane().add(panelRecMensal);
        panelRecMensal.setBounds(1120, 310, 690, 190);

        panelSaldoGeral.setBackground(new java.awt.Color(1, 10, 27));
        panelSaldoGeral.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 217, 210), java.awt.Color.lightGray)));
        panelSaldoGeral.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 217, 210));
        jLabel5.setText("Saldo geral");
        panelSaldoGeral.add(jLabel5);
        jLabel5.setBounds(220, 10, 240, 50);

        lblSaldoGeral.setBackground(new java.awt.Color(255, 255, 255));
        lblSaldoGeral.setFont(new java.awt.Font("Ebrima", 0, 36)); // NOI18N
        lblSaldoGeral.setForeground(new java.awt.Color(251, 251, 251));
        lblSaldoGeral.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelSaldoGeral.add(lblSaldoGeral);
        lblSaldoGeral.setBounds(0, 80, 690, 70);

        getContentPane().add(panelSaldoGeral);
        panelSaldoGeral.setBounds(1120, 30, 690, 190);

        lblLogo.setBackground(new java.awt.Color(123, 194, 145));
        lblLogo.setFont(new java.awt.Font("Gill Sans MT", 0, 54)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(255, 217, 210));
        lblLogo.setText("Minhas");
        lblLogo.setToolTipText("");
        getContentPane().add(lblLogo);
        lblLogo.setBounds(50, 80, 160, 50);

        lblLogo2.setBackground(new java.awt.Color(123, 194, 145));
        lblLogo2.setFont(new java.awt.Font("Gill Sans MT", 0, 54)); // NOI18N
        lblLogo2.setForeground(new java.awt.Color(255, 217, 210));
        lblLogo2.setText("Finanças");
        lblLogo2.setToolTipText("");
        getContentPane().add(lblLogo2);
        lblLogo2.setBounds(30, 120, 190, 60);

        jLabel2.setBackground(new java.awt.Color(20, 33, 56));
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(123, 194, 145), 75, true));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 200, 150, 590);

        jLabel1.setBackground(new java.awt.Color(20, 33, 56));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1940, 1100);

        menuPrincipal.setSelectionModel(null);

        jMenu1.setBackground(new java.awt.Color(102, 255, 0));
        jMenu1.setText("File");
        menuPrincipal.add(jMenu1);

        setJMenuBar(menuPrincipal);

        setSize(new java.awt.Dimension(1920, 1080));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /* MOSTRAR E FECHAR PANELS */
    private void verificarEnabled() {
        if (panelRelatorio.isEnabled() || panelDespesas.isEnabled() || panelReceitas.isEnabled() || panelOrcamentos.isEnabled() || panelMetas.isEnabled()) {
            fecharRelatorio();
            fecharDespesas();
            fecharReceitas();
            fecharOrcamentos();
            fecharMetas();
        }
    }

    /* LISTAR METAS */
    private void listarMetas(int id) throws ClassNotFoundException, SQLException {
        ResultSet meta = new minhasFinancasDao().buscarMeta(id);
        DefaultTableModel tblModelo = (DefaultTableModel) tblMetas.getModel();
        tblModelo.setRowCount(0); //limpa a tabela

        //Passa linha por linha até o final da tabela 
        while (meta.next()) {
            String linha[] = {
                meta.getString("met_id"),
                meta.getString("descricao_met"),
                meta.getString("valor_met"),
                meta.getString("data_inicial_met"),
                meta.getString("data_final_met")
            };
            tblModelo.addRow(linha);
        }
    }
    
    private void listarRelatorios(int id) throws ClassNotFoundException, SQLException {
        ResultSet relatorio = new minhasFinancasDao().gerarRelatorio(id);
        DefaultTableModel tblModelo = (DefaultTableModel) tblRelatorio.getModel();
        tblModelo.setRowCount(0); //limpa a tabela

        //Passa linha por linha até o final da tabela 
        while (relatorio.next()) {
            String linha[] = {
                relatorio.getString("Data"),
                relatorio.getString("Entrada"),
                relatorio.getString("Saida"),
                relatorio.getString("Saldo"),};
            tblModelo.addRow(linha);
        }
    }

    // Relatorio
    private void mostrarRelatorio() {
        verificarEnabled();
        panelRelatorio.setEnabled(true);
        panelRelatorio.setVisible(true);
    }

    private void fecharRelatorio() {
        panelRelatorio.setEnabled(false);
        panelRelatorio.setVisible(false);
    }

    // Despesas
    private void mostrarDespesas() {
        verificarEnabled();
        panelDespesas.setEnabled(true);
        panelDespesas.setVisible(true);
    }

    private void fecharDespesas() {
        panelDespesas.setEnabled(false);
        panelDespesas.setVisible(false);
    }

    // Receitas
    private void mostrarReceitas() {
        verificarEnabled();
        panelReceitas.setEnabled(true);
        panelReceitas.setVisible(true);
    }

    private void fecharReceitas() {
        panelReceitas.setEnabled(false);
        panelReceitas.setVisible(false);
    }

    // Orçamentos
    private void mostrarOrcamentos() {
        verificarEnabled();
        panelOrcamentos.setEnabled(true);
        panelOrcamentos.setVisible(true);
    }

    private void fecharOrcamentos() {
        panelOrcamentos.setEnabled(false);
        panelOrcamentos.setVisible(false);
    }

    // Metas
    private void mostrarMetas() {
        verificarEnabled();
        panelMetas.setEnabled(true);
        panelMetas.setVisible(true);
    }

    private void fecharMetas() {
        panelMetas.setEnabled(false);
        panelMetas.setVisible(false);
    }

    /* BOTÕES */
    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed

        if (panelRelatorio.isEnabled()) {
            fecharRelatorio();
        } else {
            mostrarRelatorio();
        }

        try {
            listarRelatorios(id);
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRelatorioActionPerformed

    private void btnDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDespesasActionPerformed

        if (panelDespesas.isEnabled()) {
            fecharDespesas();
        } else {
            mostrarDespesas();
        }
    }//GEN-LAST:event_btnDespesasActionPerformed

    private void btnReceitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceitasActionPerformed

        if (panelReceitas.isEnabled()) {
            fecharReceitas();
        } else {
            mostrarReceitas();
        }
    }//GEN-LAST:event_btnReceitasActionPerformed

    private void btnMetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetasActionPerformed
        if (panelMetas.isEnabled()) {
            fecharMetas();
        } else {
            mostrarMetas();
        }

        // Listar Metas
        try {
            listarMetas(id);

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnMetasActionPerformed

    private void panelReceitasAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_panelReceitasAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_panelReceitasAncestorRemoved

    private void txtValorDespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorDespActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorDespActionPerformed

    private void btnCriarReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarReceitaActionPerformed
        // CRIAR RECEITA
       double valorRec = 0;
        try {
            valorRec = Double.valueOf(txtValorRec.getText());
          
            
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane, "O valor deve ser numérico", "", JOptionPane.INFORMATION_MESSAGE);
            txtValorDesp.requestFocus();
            return;
        }
        String descricaoRec = txtDescricaoRec.getText();
        String dataRec = txtDataRec.getText();
        String categoriaRec = cmbCategoriaRec.getSelectedItem().toString();

        if (descricaoRec.isEmpty() || dataRec.isBlank() || categoriaRec.isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "Os espaços devem ser preenchidos corretamente.", "", JOptionPane.INFORMATION_MESSAGE);
        } else try {
            // Chama classe Dao
            new minhasFinancasDao().criarReceita(descricaoRec, valorRec, dataRec, categoriaRec, id);

            // limpar os campos
            txtDescricaoRec.setText("");
            txtValorRec.setText("");
            txtDataRec.setText("");

            JOptionPane.showMessageDialog(rootPane, "Receita cadastrada!", "", JOptionPane.INFORMATION_MESSAGE);

            // posicina cursor em descrição
            txtDescricaoRec.requestFocus();

            //MOSTRA DESPESA MENSAL
            lblMostrarReceita.setText(new minhasFinancasDao().mostrarReceita(id));

            //MOSTRA SALDO GERAL
            lblSaldoGeral.setText(new minhasFinancasDao().saldoGeral(id));
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Entre em contato com o suporte e informe o erro: " + ex.getMessage(), "Erro", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCriarReceitaActionPerformed

    private void btnCriarMetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarMetaActionPerformed
        // CRIAR META
        double valorMeta = 0;
        try {
            valorMeta = Double.valueOf(txtValorMeta.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane, "O valor deve ser numérico", "", JOptionPane.INFORMATION_MESSAGE);
            txtValorDesp.requestFocus();
            return;
        }
        String descricaoMeta = txtDescricaoMeta.getText();
        String inicioMeta = txtDataInicialMeta.getText();
        String fimMeta = txtDataFinalMeta.getText();

        if (descricaoMeta.isBlank() || inicioMeta.isBlank() || fimMeta.isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "Os espaços devem ser preenchidos corretamente.", "", JOptionPane.INFORMATION_MESSAGE);
        } else try {
            // Chama classe Dao
            new minhasFinancasDao().criarMeta(descricaoMeta, valorMeta, inicioMeta, fimMeta, id);
            listarMetas(id);

            // limpar os campos
            txtDescricaoMeta.setText("");
            txtValorMeta.setText("");
            txtDataInicialMeta.setText("");
            txtDataFinalMeta.setText("");

            JOptionPane.showMessageDialog(rootPane, "Meta cadastrada!", "", JOptionPane.INFORMATION_MESSAGE);

            // posicina cursor em descrição
            txtDescricaoMeta.requestFocus();

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Entre em contato com o suporte e informe o erro: " + ex.getMessage(), "Erro", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCriarMetaActionPerformed

    private void btnCriarDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarDespesaActionPerformed

        // CRIAR DESPESA
        double valorDesp = 0;
        try {
            valorDesp = Double.valueOf(txtValorDesp.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane, "O valor deve ser numérico", "", JOptionPane.INFORMATION_MESSAGE);
            txtValorDesp.requestFocus();
            return;
        }
        String descricaoDesp = txtDescricaoDesp.getText();
        String dataDesp = txtDataDesp.getText();
        String categoriaDesp = cmbCategoriaDesp.getSelectedItem().toString();

        if (descricaoDesp.isBlank() || dataDesp.isBlank() || categoriaDesp.isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "Os espaços devem ser preenchidos corretamente.", "", JOptionPane.INFORMATION_MESSAGE);
        } else try {
            // Chama classe Dao
            new minhasFinancasDao().criarDespesa(descricaoDesp, valorDesp, dataDesp, categoriaDesp, id);
            // limpar os campos
            txtDescricaoDesp.setText("");
            txtValorDesp.setText("");
            txtDataDesp.setText("");

            JOptionPane.showMessageDialog(rootPane, "Despesa cadastrada!", "", JOptionPane.INFORMATION_MESSAGE);

            // posicina cursor em descrição
            txtDescricaoDesp.requestFocus();

            //MOSTRA DESPESA MENSAL
            lblMostrarDespesa.setText(new minhasFinancasDao().mostrarDespesa(id));

            //MOSTRA SALDO GERAL
            lblSaldoGeral.setText(new minhasFinancasDao().saldoGeral(id));

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Entre em contato com o suporte e informe o erro: " + ex.getMessage(), "Erro", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCriarDespesaActionPerformed

    private void txtDataDespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataDespActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataDespActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            //MOSTRA DESPESA MENSAL
            lblMostrarDespesa.setText(new minhasFinancasDao().mostrarDespesa(id));

            //MOSTRA RECEITA MENSAL
            lblMostrarReceita.setText(new minhasFinancasDao().mostrarReceita(id));

            //MOSTRA SALDO GERAL
            lblSaldoGeral.setText(new minhasFinancasDao().saldoGeral(id));

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(PaginaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowActivated

    private void btnExcluirMetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirMetaActionPerformed
        int numMeta = Integer.parseInt(JOptionPane.showInputDialog(rootPane, "Insira o N° da meta que deseja excluir:"));
        try {
            new minhasFinancasDao().excluirMeta(numMeta);
            listarMetas(id);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(PaginaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnExcluirMetaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatDarculaLaf.setup();
        UIManager.put("TitlePane.unifiedBackground", false);
        UIManager.put("TitlePane.background", new ColorUIResource(1, 10, 27));
        UIManager.put("TitlePane.foreground", Color.WHITE);
        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(() -> {
                new PaginaPrincipal().setVisible(true);
            });
        } catch (UnsupportedLookAndFeelException ex) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriarDespesa;
    private javax.swing.JButton btnCriarMeta;
    private javax.swing.JButton btnCriarReceita;
    private javax.swing.JButton btnDespesas;
    private javax.swing.JButton btnExcluirMeta;
    private javax.swing.JButton btnMetas;
    private javax.swing.JButton btnReceitas;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JComboBox<String> cmbCategoriaDesp;
    private javax.swing.JComboBox<String> cmbCategoriaRec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JLabel lblDespMen;
    private javax.swing.JLabel lblFundoDespesa;
    private javax.swing.JLabel lblFundoOrcamento;
    private javax.swing.JLabel lblFundoReceitas;
    private javax.swing.JLabel lblFundoRelatorio;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogo2;
    public javax.swing.JLabel lblMostrarDespesa;
    private javax.swing.JLabel lblMostrarReceita;
    private javax.swing.JLabel lblRecMen1;
    private javax.swing.JLabel lblSaldoGeral;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JLabel lblTexto1;
    private javax.swing.JLabel lblTexto10;
    private javax.swing.JLabel lblTexto11;
    private javax.swing.JLabel lblTexto2;
    private javax.swing.JLabel lblTexto3;
    private javax.swing.JLabel lblTexto4;
    private javax.swing.JLabel lblTexto5;
    private javax.swing.JLabel lblTexto6;
    private javax.swing.JLabel lblTexto7;
    private javax.swing.JLabel lblTexto8;
    private javax.swing.JLabel lblTexto9;
    private javax.swing.JLabel lblTituloDespesa;
    private javax.swing.JLabel lblTituloMetas;
    private javax.swing.JLabel lblTituloOrcamento;
    private javax.swing.JLabel lblTituloReceitas;
    private javax.swing.JLabel lblTituloRelatorio;
    private javax.swing.JLabel lblfundoMetas;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JPanel panelDesMensal;
    private javax.swing.JPanel panelDespesas;
    private javax.swing.JPanel panelMetas;
    private javax.swing.JPanel panelOrcamentos;
    private javax.swing.JPanel panelRecMensal;
    private javax.swing.JPanel panelReceitas;
    private javax.swing.JPanel panelRelatorio;
    private javax.swing.JPanel panelSaldoGeral;
    private javax.swing.JScrollPane scrPanelMetas;
    private javax.swing.JScrollPane scrPanelRelatorio;
    private javax.swing.JTable tblMetas;
    private javax.swing.JTable tblRelatorio;
    private javax.swing.JFormattedTextField txtDataDesp;
    private javax.swing.JFormattedTextField txtDataFinalMeta;
    private javax.swing.JFormattedTextField txtDataInicialMeta;
    private javax.swing.JFormattedTextField txtDataRec;
    private javax.swing.JTextField txtDescricaoDesp;
    private javax.swing.JTextField txtDescricaoMeta;
    private javax.swing.JTextField txtDescricaoRec;
    private javax.swing.JTextField txtValorDesp;
    private javax.swing.JTextField txtValorMeta;
    private javax.swing.JTextField txtValorRec;
    // End of variables declaration//GEN-END:variables
}
